services:
  discord-bot:
    build: .
    volumes:
      - bot-data:/usr/local/share/discord-bot
    environment:
      - RUST_LOG=info
    restart: unless-stopped

volumes:
  bot-data:
    driver: local
