services:
  discord-bot:
    build: 
      context: .
      shm_size: '2gb'
    volumes:
      - bot-data:/usr/local/share/discord-bot
    environment:
      - RUST_LOG=info
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped

volumes:
  bot-data:
    driver: local
