name: Shuttle Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Shuttle
        run: cargo install cargo-shuttle
      - name: Deploy to Shuttle
        env:
          SHUTTLE_API_KEY: ${{ env.SHUTTLE_API_KEY }}
          DISCORD_TOKEN: ${{ env.DISCORD_TOKEN }}
        run: |
          echo "DISCORD_TOKEN=\"$DISCORD_TOKEN\"" > Secrets.toml
          cargo shuttle deploy --allow-dirty
