name: Shuttle deploy

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Add secrets
        run: |
          # Generate Secrets file
          echo 'DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN }}"' >> Secrets.toml
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
          allow-dirty: true
